package com.winbu
import com.baseprovider.streamix.ProviderExtractorsNative
import com.baseprovider.streamix.StreamixRuntime
import streamix.core.*
import java.net.URLEncoder
class WinbuProvider: StreamixProvider {
 override val id="winbu"; private val base="https://winbu.org"
 private suspend fun get(u:String,r:String=base)=StreamixRuntime.http?.get(u,headers=mapOf("User-Agent" to "Mozilla/5.0"),referer=r)
 override suspend fun search(q:String,page:Int)=get(base+"/?s="+URLEncoder.encode(q,"UTF-8"))?.document?.select("div.a-item,div.ml-item,div.ml-item-anime")?.mapNotNull{e->val a=e.selectFirst("a.ml-mask")?:return@mapNotNull null;ProviderAnime(id,a.absUrl("href"),a.selectFirst(".judul")?.text()?.trim()?:a.attr("title"),a.absUrl("href"),e.selectFirst("img.mli-thumb")?.absUrl("src"))}?.distinctBy{it.url}?:emptyList()
 override suspend fun detail(a:ProviderAnime):ProviderAnime?{val d=get(a.url)?.document?:return null;val t=d.selectFirst(".m-info .judul")?.text()?.trim()?:d.selectFirst("meta[property=og:title]")?.attr("content")?.replace(Regex("(?i)\\s*-\\s*Winbu.*"),"")?.trim()?:a.title;return a.copy(title=t,poster=d.selectFirst(".m-info img.mli-thumb,meta[property=og:image]")?.let{it.attr("content").ifBlank{it.attr("src")}}?.let{if(it.startsWith("http"))it else java.net.URI(a.url).resolve(it).toString()}?:a.poster,description=d.selectFirst(".m-info .mli-desc,meta[name=description]")?.let{it.attr("content").ifBlank{it.text()}})}
 override suspend fun episodes(a:ProviderAnime):List<ProviderEpisode>{val d=get(a.url)?.document?:return emptyList();return d.select("div.les-content a,div.tvseason a,ul.episod li a,.eplister a").mapNotNull{e->val u=e.absUrl("href");if(u.isBlank())return@mapNotNull null;val n=Regex("(?i)Episode\\s*(\\d+)").find(e.text())?.groupValues?.get(1)?.toIntOrNull()?:Regex("(?i)-episode-(\\d+)").find(u)?.groupValues?.get(1)?.toIntOrNull();ProviderEpisode(id+"-"+(n?:0),n?:1,u,e.text().trim(),u)}.distinctBy{it.url}.sortedBy{it.number}}
 override suspend fun streams(e:ProviderEpisode):List<ProviderStream>{val d=get(e.url,e.url)?.document?:return emptyList();val out=mutableListOf<ProviderStream>();d.select("div.east_player_option").forEach{el->val post=el.attr("data-post");val nume=el.attr("data-nume");if(post.isBlank()||nume.isBlank())return@forEach;val form=mapOf("action" to "player_ajax","post" to post,"nume" to nume,"type" to el.attr("data-type").ifBlank{"schtml"}).entries.joinToString("&"){java.net.URLEncoder.encode(it.key,"UTF-8")+"="+java.net.URLEncoder.encode(it.value,"UTF-8")};val body=StreamixRuntime.http?.post(base+"/wp-admin/admin-ajax.php",body=form,headers=mapOf("X-Requested-With" to "XMLHttpRequest","Content-Type" to "application/x-www-form-urlencoded"),referer=e.url)?:return@forEach;val src=Regex("""src=["']([^"']+)["']""").find(body.text)?.groupValues?.get(1)?:Regex("""https?://[^\s"'<>]+""").find(body.text)?.value;if(!src.isNullOrBlank()){ProviderExtractorsNative.resolve(src,e.url){x->out+=ProviderStream(id+"-"+out.size,x.url,x.quality,x.type.name.lowercase(),headers=x.headers,referer=x.referer)}}};d.select("div.pframe iframe,.movieplay iframe,.player iframe,iframe[src]").forEach{e2->val u=e2.attr("src").ifBlank{e2.attr("data-src")};if(u.isNotBlank()&&!u.contains("youtube",true))ProviderExtractorsNative.resolve(e2.absUrl("src"),e.url){x->out+=ProviderStream(id+"-"+out.size,x.url,x.quality,x.type.name.lowercase(),headers=x.headers,referer=x.referer)}};return out.distinctBy{it.url}}
}