package com.animesail
import com.baseprovider.streamix.ProviderExtractorsNative
import com.baseprovider.streamix.StreamixRuntime
import streamix.core.*
import java.net.URLEncoder
class AnimeSailProvider : StreamixProvider {
 override val id="animesail"; private val base="https://anisail.com"; private val headers=mapOf("User-Agent" to "Mozilla/5.0")
 private suspend fun get(u:String,r:String=base)=StreamixRuntime.http?.get(u,headers=headers,referer=r,cookies=mapOf("_as_ipin_ct" to "ID","_as_ipin_tz" to "Asia/Jakarta","_as_ipin_lc" to "id-ID"))
 private fun abs(s:String,p:String=base)=if(s.startsWith("http",true))s else java.net.URI(p).resolve(s).toString()
 override suspend fun search(q:String,page:Int)=get(base+"/?s="+URLEncoder.encode(q,"UTF-8"))?.document?.select("div.listupd article")?.mapNotNull{e->val a=e.selectFirst("a")?:return@mapNotNull null;var u=abs(a.attr("href"));if(!u.contains("/anime/"))u=base+"/anime/"+u.substringAfter(base+"/").removeSuffix("/");val t=e.selectFirst(".tt > h2")?.text()?.replace(Regex("(?i)Episode\\s*\\d+|Subtitle Indonesia|Sub Indo"),"")?.trim()?:return@mapNotNull null;ProviderAnime(id,u,t,u,e.selectFirst("div.limit img")?.attr("src")?.let{abs(it)})}?.distinctBy{it.url}?:emptyList()
 override suspend fun detail(a:ProviderAnime):ProviderAnime?{val d=get(a.url)?.document?:return null;val t=(d.selectFirst("h1.entry-title")?.text()?:d.title()).replace("Subtitle Indonesia","").trim();val p=d.selectFirst("div.entry-content > img,meta[property=og:image]")?.let{it.attr("src").ifBlank{it.attr("content")}}?.let{abs(it,a.url)};val desc=d.selectFirst("div.entry-content > p")?.text()?.trim();val tags=d.select("tbody th:contains(Genre)").next().select("a").map{it.text().trim()};return a.copy(title=t,poster=p?:a.poster,description=desc,tags=tags)}
 override suspend fun episodes(a:ProviderAnime):List<ProviderEpisode>{val d=get(a.url)?.document?:return emptyList();return d.select("ul.daftar > li").mapNotNull{e->val x=e.selectFirst("a")?:return@mapNotNull null;val n=Regex("Episode\\s*(\\d+)",RegexOption.IGNORE_CASE).find(x.text())?.groupValues?.get(1)?.toIntOrNull()?:return@mapNotNull null;val u=abs(x.attr("href"),a.url);ProviderEpisode(id,n,u,x.text().trim(),u)}.distinctBy{it.id}.sortedBy{it.number}}
 override suspend fun streams(e:ProviderEpisode):List<ProviderStream>{val d=get(e.url,e.url)?.document?:return emptyList();val out=mutableListOf<ProviderStream>();d.select("iframe[src],source[src],video[src],.mobius .mirror option").forEach{el->val raw=el.attr("src").ifBlank{el.attr("value")}.ifBlank{el.attr("data-em")};if(raw.isBlank())return@forEach;val u=abs(raw,e.url);if(u.contains(".m3u8",true)||u.contains(".mp4",true))out+=ProviderStream(id,u,Regex("\\d{3,4}").find(u)?.value?.toIntOrNull(),if(u.contains(".m3u8",true))"m3u8" else "video",referer=e.url)else runCatching{ProviderExtractorsNative.resolve(u,e.url){r->out+=ProviderStream(id,r.url,r.quality,r.type.name.lowercase(),headers=r.headers,referer=r.referer.takeIf{it.isNotBlank()})}}};return out.distinctBy{it.url}}
}